import Head from 'next/head'
import style from '../styles/404.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/68c6324e4e.js"></script>
      </Head>
      <div className="bodyCa">
        <div className="cont">
          {/* Here is the content container starts */}
          <div className={style.container_2}>
            <div className={style.verification_form_card}>
              <h1>Din păcate nu găsim ceea ce cauți :\</h1>
              <div className={style.create_inputs}>
                <p>Verifică dacă adresa site-ului este scrisă corect</p>
                <p>
                  sau du-te la pagina de început <Link href="/index">aici</Link>
                </p>
              </div>
            </div>
            <div className={style.gym_text}>
              <h1>Grow</h1>
              <h2>Your</h2>
              <h1 className={style.music_gym}>Music</h1>
            </div>
            <div className={style.gym_text_back}>
              <h1>Grow</h1>
              <h2>Your</h2>
              <h1 className={style.music_gym_back}>Music</h1>
            </div>
            <img src="/img/artist.png" alt="" className={style.artist} />
          </div>
          {/* Here is the content container ends */}
        </div>
      </div>
    </div>
  )
}
