import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/changeprofile.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Change Profile </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.r_side}>
                  <div className={style.changeimg_input}>
                    <h1>Imaginea de profil</h1>
                    <input
                      style={{ display: "none" }}
                      type="file"
                      name="imgInput"
                      id="fileInputImg"
                      accept="image/png, image/jpeg, image/jpg"
                    />
                    <label htmlFor="fileInputImg">
                      <h2 className={style.img__label}>Apasă pentru a schimba imaginea</h2>
                    </label>
                  </div>
                  <div className={style.artistname_input}>
                    <h1>Nume de scenă</h1>
                    <input type="text" placeholder="Schimbă numele de scenă..." />
                  </div>
                  <div className={style.featurefee_input}>
                    <h1>Preţ de colaborare</h1>
                    <input type="text" placeholder="Schimbă preţul de colaborare..." />
                  </div>
                  <div className={style.artistname_input}>
                    <h1>Descriere</h1>
                    <textarea
                      placeholder="Schimbă descrierea..."
                      defaultValue={""}
                    />
                  </div>
                  <Link href="feed">
                    <div className={style.savechanges}>
                      <input type="submit" defaultValue="Salvează" />
                    </div>
                  </Link>
                </div>
              </div>
              <div className={style.profile_bar}>
                <div className={style.user_detail}>
                  <div className={style.user_detail_with_image}>
                    <div className={style.profile_pic}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                    </div>
                    <div className={style.feat}>
                      <h3 className={style.full_name}>Demo Account</h3>
                      <h3 className={style.username}>@Username</h3>
                      <p>Preţ de colaborare:</p>
                      <span>$300M</span>
                    </div>
                  </div>

                  <div className={style.bio}>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Enim, nihil
                      cumque! Quos voluptates quae ea soluta porro tempora nam illum dicta
                      autem cum saepe, voluptatem exercitationem, inventore fugiat pariatur
                      atque!
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
