import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/chat.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat -- Growwithmusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.user_info}>
                    <div className={style.left}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.info}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p className={style.username}><b>loremipsum</b></p>
                      </div>
                    </div>
                    <div className={style.gotoprofile}>
                      <Link href="/userprofile">
                        <h4>Vizitează profilul</h4>
                        <i className="fa-solid fa-arrow-right-long" />
                      </Link>
                    </div>
                  </div>
                  <div className={style.chat}>
                    <div className={style.newrow}>
                      <div className={`${style.recived} ${style.msg_box}`}>
                        <p>Salut</p>
                        <h6 className={style.time}>11:11 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.sent} ${style.msg_box}`}>
                        <p>
                          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum
                          placeat et facere inventore. Animi incidunt, a perspiciatis maiores
                          illum ipsum quibusdam commodi adipisci ratione ex soluta autem,
                          consequuntur necessitatibus eligendi.
                        </p>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.recived} ${style.msg_box} ${style.contract}`}>
                        <Link href="/acceptcontract">
                          <p>
                            <i className="fas fa-file-signature" />
                            Ai primit un contract de colaborare
                          </p>
                        </Link>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.sent} ${style.msg_box} ${style.contract}`}>
                        <Link href="/acceptcontractws">
                          <p>
                            <i className="fas fa-file-signature" />
                            Ai trimis un contract de colaborare
                          </p>
                        </Link>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.recived} ${style.msg_box}`}>
                        <p>Salut</p>
                        <h6 className={style.time}>11:11 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.sent} ${style.msg_box}`}>
                        <p>
                          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum
                          placeat et facere inventore. Animi incidunt, a perspiciatis maiores
                          illum ipsum quibusdam commodi adipisci ratione ex soluta autem,
                          consequuntur necessitatibus eligendi.
                        </p>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.recived} ${style.msg_box} ${style.contract}`}>
                        <Link href="/acceptcontract">
                          <p>
                            <i className="fas fa-file-signature" />
                            Ai primit un contract de colaborare
                          </p>
                        </Link>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.sent} ${style.msg_box} ${style.contract}`}>
                        <Link href="/acceptcontractws">
                          <p>
                            <i className="fas fa-file-signature" />
                            Ai trimis un contract de colaborare
                          </p>
                        </Link>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.recived} ${style.msg_box}`}>
                        <p>Salut</p>
                        <h6 className={style.time}>11:11 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.sent} ${style.msg_box}`}>
                        <p>
                          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum
                          placeat et facere inventore. Animi incidunt, a perspiciatis maiores
                          illum ipsum quibusdam commodi adipisci ratione ex soluta autem,
                          consequuntur necessitatibus eligendi.
                        </p>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.recived} ${style.msg_box} ${style.contract}`}>
                        <Link href="/acceptcontract">
                          <p>
                            <i className="fas fa-file-signature" />
                            Ai primit un contract de colaborare
                          </p>
                        </Link>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                    <div className={style.newrow}>
                      <div className={`${style.sent} ${style.msg_box} ${style.contract}`}>
                        <Link href="/acceptcontractws">
                          <p>
                            <i className="fas fa-file-signature" />
                            Ai trimis un contract de colaborare
                          </p>
                        </Link>
                        <h6 className={style.time}>11:68 AM</h6>
                      </div>
                    </div>
                  </div>
                  <div className={style.send_input}>
                    <input type="text" id="msgInput" className={style.msgInput} placeholder="Say Hello...!!" />
                    <i className="fas fa-paper-plane" id="sendmsg" />
                    <Link href="/contracts">
                      <i className="fas fa-file-signature" id="sendcon" />
                    </Link>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>

                <div className={style.frow}>
                  <h5>Listă Contracte</h5>
                  <Link
                    href="/chat"
                    style={{
                      width: 180,
                      borderRadius: "5px",
                      cursor: "pointer",
                      display: "flex",
                      padding: "10px ",
                      color: "white",
                      backgroundColor: "#6657DA"
                    }}
                  >
                    <h4 style={{ fontSize: 14 }}>Verifică-ți mesajele</h4>
                    <i
                      className="fa-solid fa-arrow-right-long"
                      style={{ marginLeft: 145, marginTop: 3 }}
                    />
                  </Link>
                </div>
                <ul>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                </ul>

              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
