import Head from 'next/head'
import style from '../styles/createnew.module.css'
import Navbar from '../components/navbar'
import { useState, useRef } from 'react'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import Link from 'next/link'
import { BiArrowBack } from "react-icons/bi";
import Script from 'next/script'

export default function Home() {

  const [videopost, setVideoPost] = useState(false)
  const [imgpost, setImgpost] = useState(false)
  const [textpost, setTextpost] = useState(false)
  const [allpost, setAllPost] = useState(true)


  const hanlderClick = (e: any) => {

    if (e.target.name == "text") {
      setAllPost(false)
      setVideoPost(false)
      setImgpost(false)
      setTextpost(true)
    } else if (e.target.name == "video") {
      setVideoPost(true)
      setImgpost(false)
      setTextpost(false)
      setAllPost(false)
    } else if (e.target.name == "img") {
      setVideoPost(false)
      setImgpost(true)
      setTextpost(false)
      setAllPost(false)
    }
  }

  const hanlderClickBack = () => {
    setVideoPost(false)
    setImgpost(false)
    setTextpost(false)
    setAllPost(true)
  }

  console.log("Video Post :", videopost);
  console.log("Img Post :", imgpost);
  console.log("Text Post :", textpost);
  const ref = useRef();

  return (
    <>
      <Head>
        <title>Create New Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  {allpost && <div className={style.p1}>
                    <h1>Selectează tipul de postare:</h1>
                    <div className={style.options}>
                      <div className={`${style.option} ${style.video_card}`}>

                        <div className={style.card_cont}>
                          <h2>VIDEO</h2>
                          <p>
                            Postează un video pentru a le arăta și celorlalți utilizatori o
                            parte din viitoarele tale proiecte.
                          </p>
                          <button id="selectVid" name='video' onClick={hanlderClick}>Selectează</button>
                          <i className="fa-solid fa-video" />
                        </div>
                      </div>
                      <div className={`${style.option} ${style.text_card}`}>

                        <div className={style.card_cont}>
                          <h2>TEXT</h2>
                          <p>
                            Împărtășește-ți gândurile cu alți utilizatori prin postarea text.
                          </p>
                          <button id="selectTxt" name='text' onClick={hanlderClick}>Selectează</button>
                          <i className="fa-solid fa-quote-left" />
                        </div>
                      </div>
                      <div className={`${style.option} ${style.img_card}`}>

                        <div className={style.card_cont}>
                          <h2>POZĂ</h2>
                          <p>
                            Postează o poză pentru a le arăta și altor utilizatori momente din
                            cariera ta muzicală.
                          </p>
                          <button id="selectImg" name='img' onClick={hanlderClick}>Selectează</button>
                          <i className="fa-solid fa-camera" />
                        </div>
                      </div>
                    </div>
                  </div>}

                  {videopost && <div className={style.video_post}>
                    <div className={style.back}>
                      <button onClick={hanlderClickBack}><BiArrowBack /></button>
                    </div>
                    <h1 className={style.titlee}>Creează o postare video</h1>
                    <div className={style.post} id="postCreate">
                      <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                      <div className={style.fullpost}>
                        <div className={style.post_cont}>
                          <input
                            type="file"
                            name="videoInput"
                            id="fileInput"
                            accept="video/mp4,video/x-m4v,video/*"
                          />
                          <label htmlFor="fileInput">
                            <i className="fa-solid fa-circle-plus" />
                          </label>
                          <video
                            preload="auto"
                            controlsList="nodownload"
                            disablePictureInPicture={true}
                            className="fixed-aspect-ratio"
                            id="videoP"
                          >
                            <source id="source" />
                          </video>
                        </div>
                        <div className={style.post_info}>
                          <p className={style.username_post}>loremipsum</p>
                          <textarea
                            placeholder="Scrie aici ceva..."
                            rows={2}
                            defaultValue={""}
                          />
                        </div>
                        <div className={style.like_boxx}>
                          <i className="fa-solid fa-volume-high" id="like" />
                        </div>
                      </div>
                    </div>
                    <input type="submit" className={style.submit_btn} defaultValue="Creează postarea" id="vidPostSubmit" />
                  </div>}

                  {textpost && <div className={style.text_post}>
                    <div className={style.back}>
                      <button onClick={hanlderClickBack}><BiArrowBack /></button>
                    </div>
                    <h1 className={style.titlee}>Creează o postare text</h1>
                    <div className={style.post} id="postCreate">
                      <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                      <div className={style.fullpost}>
                        <div className={`${style.post_info} ${style.post_info1}`}>
                          <p className={style.username_post}>loremipsum</p>
                          <textarea
                            placeholder="Scrie aici ceva..."
                            rows={10}
                            defaultValue={""}
                          />
                        </div>
                        <div className={style.like_boxx}>
                          <i className="fa-solid fa-volume-high" id="like" />
                        </div>
                      </div>
                    </div>
                    <input type="submit" className={style.submit_btn} defaultValue="Creează postarea" id="txtPostSubmit" />
                  </div>}

                  {imgpost && <div className={style.img_post}>
                    <div className={style.back}>
                      <button onClick={hanlderClickBack}><BiArrowBack /></button>
                    </div>
                    <h1 className={style.titlee}>Creează postare tip poză</h1>
                    <div className={style.post} id="postCreate">
                      <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                      <div className={style.fullpost}>
                        <div className={style.post_cont}>
                          <input
                            type="file"
                            name="imgInput"
                            id="fileInputImg"
                            accept="image/png, image/jpeg, image/jpg"
                          />
                          <label htmlFor="fileInputImg">
                            <i className="fa-solid fa-circle-plus" />
                          </label>
                          <div className={style.image}>
                            <img src="" alt="" id="imgP" />
                          </div>
                        </div>
                        <div className={style.post_info}>
                          <p className={style.username_post}>loremipsum</p>
                          <textarea
                            placeholder="Scrie aici ceva..."
                            rows={2}
                            defaultValue={""}
                          />
                        </div>
                        <div className={style.like_boxx}>
                          <i className="fa-solid fa-volume-high" id="like" />
                        </div>
                      </div>
                    </div>
                    <input type="submit" className={style.submit_btn} defaultValue="Creează postarea" id="imgPostSubmit" />
                  </div>}
                </div>
              </div>
              <div className={style.profile_bar}>

                <div className={style.frow}>
                  <h5>Listă Contracte</h5>
                  <Link
                    href="/chat"
                    style={{
                      width: 180,
                      borderRadius: "5px",
                      cursor: "pointer",
                      display: "flex",
                      padding: "10px ",
                      color: "white",
                      backgroundColor: "#6657DA"
                    }}
                  >
                    <h4 style={{ fontSize: 14 }}>Verifică-ți mesajele</h4>
                    <i
                      className="fa-solid fa-arrow-right-long"
                      style={{ marginLeft: 145, marginTop: 3 }}
                    />
                  </Link>
                </div>
                <ul>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                </ul>

              </div>

            </div>

          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
