import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { FaSignOutAlt } from "react-icons/fa";
import { IoMdNotifications } from "react-icons/io";
import { BsFillGearFill } from "react-icons/bs";
import style from '../styles/errorplata.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Accept Contract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.verification_form_card}>
                    <h1>Ne pare rău, tranzacția nu s-a putut realiza</h1>
                    <div className={style.create_inputs}>
                      <p>Verifică dacă datele cardului sunt valide și corect completate!</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>

                <div className={style.frow}>
                  <h5>Listă Contracte</h5>
                  <Link
                    href="/chat"
                    style={{
                      width: 180,
                      borderRadius: "5px",
                      cursor: "pointer",
                      display: "flex",
                      padding: "10px ",
                      color: "white",
                      backgroundColor: "#6657DA"
                    }}
                  >
                    <h4 style={{ fontSize: 14 }}>Verifică-ți mesajele</h4>
                    <i
                      className="fa-solid fa-arrow-right-long"
                      style={{ marginLeft: 145, marginTop: 3 }}
                    />
                  </Link>
                </div>
                <ul>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                </ul>

              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
