import Head from 'next/head'
import { AiOutlineSearch, AiFillHeart } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/feed.module.css'
import { useEffect, useState } from 'react'
import Navbar from '../components/navbar'
import { useRouter } from 'next/router'
import { parseCookies, setCookie, destroyCookie } from 'nookies'
import Link from 'next/link';
import Script from 'next/script'

export default function Home(props: any) {

  const router = useRouter();

  const [username, setUsername] = useState()
  const [userdata, setUserData] = useState()
  const [useremail, setUserEmail] = useState()

  // console.log(props);

  return (
    <>
      <Head>
        <title>Feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/68c6324e4e.js" crossOrigin="anonymous" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.post}>
                  <div className={style.user_detcontent}>
                    <div className={style.user_details}>

                      <div className={style.user_pic}>
                        <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                      </div>
                      <div className={style.user_name}><b>username</b></div>
                    </div>
                    <i className="fa-solid fa-ellipsis" />

                  </div>
                  <div className={style.post_cont}>
                    <img src="/img/artwork.jpeg" alt="" />
                  </div>
                  <div className={style.post_info}>
                    <div>
                      <div className={style.user_name}><b>username</b></div>
                      <h3>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor
                        accusamus omnis inventore ullam doloremque necessitatibus, mollitia
                        debitis dolorem provident, saepe vero corrupti molestias sint ad
                        nostrum sit in ut earum.
                      </h3>
                    </div>
                    <div className={`${style.like_btn} ${style.liked}`}>
                      <i className="fa-solid fa-volume-high" />
                    </div>
                  </div>
                </div>
                <div className={style.post}>
                  <div className={style.user_detcontent}>
                    <div className={style.user_details}>

                      <div className={style.user_pic}>
                        <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                      </div>
                      <div className={style.user_name}><b>username</b></div>
                    </div>
                    <i className="fa-solid fa-ellipsis" />

                  </div>
                  <div className={style.post_contvid}>
                    <video src="/img/studio.mp4" autoPlay controls loop muted preload="true"></video>
                  </div>
                  <div className={style.post_info}>
                    <div>
                      <div className={style.user_name}><b>username</b></div>
                      <h3>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor
                        accusamus omnis inventore ullam doloremque necessitatibus, mollitia
                        debitis dolorem provident, saepe vero corrupti molestias sint ad
                        nostrum sit in ut earum.
                      </h3>
                    </div>
                    <div className={`${style.like_btn} ${style.liked}`}>
                      <i className="fa-solid fa-volume-high" />
                    </div>
                  </div>
                </div>
                <div className={style.post}>
                  <div className={style.user_detcontent}>
                    <div className={style.user_details}>

                      <div className={style.user_pic}>
                        <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                      </div>
                      <div className={style.user_name}><b>username</b></div>
                    </div>
                    <i className="fa-solid fa-ellipsis" />

                  </div>
                  <div className={style.post_conttxt}>
                    <h3>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor
                      accusamus omnis inventore ullam doloremque necessitatibus, mollitia
                      debitis dolorem provident, saepe vero corrupti molestias sint ad
                      nostrum sit in ut earum.
                    </h3>
                  </div>
                  <div className={style.post_info}>

                    <div className={`${style.like_btn} `}>
                      <i className="fa-solid fa-volume-high" />
                    </div>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>
                <div className={style.user_detail}>
                  <div className={style.user_detail_with_image}>
                    <div className={style.profile_pic}>
                      <img src="/img/Group 1 (3).png" alt="" className={style.profileimg} />
                    </div>
                    <div className={style.feat}>
                      <h3 className={style.full_name}>Nume de scenă:</h3>
                      <h3 className={style.username}><b>STAGE NAME</b></h3>

                    </div>
                  </div>
                  <div className={style.price}>
                    <h3 className={style.price_title}>Preț de colaborare:</h3>
                    <h3 className={style.pricee}><b>2500RON</b></h3>

                  </div>
                  <div className={style.bio}>
                    <h3 className={style.bio_title}>
                      Descriere:
                    </h3>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Enim, nihil
                      cumque! Quos voluptates quae ea soluta porro tempora nam illum dicta
                      autem cum saepe, voluptatem exercitationem, inventore fugiat pariatur
                      atque!
                    </p>
                  </div>
                  <div className={style.edit}>
                    <button><h4>Editează</h4></button>
                  </div>
                </div>
                <div className={style.news_card}>
                  <h1>Verifică noutăţile #GrowYourMusic!</h1>
                  <p>Citeşte ultimele notificări primite.</p>
                  <p className={style.news_pb}>
                    <b>#GrowYourMusicDELUXEComingSoon</b>
                  </p>
                  <Link href="/news">
                    <button><h4>Verifică-le aici</h4></button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}


// export async function getServerSideProps(ctx: any) {

//   const { token } = parseCookies(ctx)

//   if (!token) {
//     const { res } = ctx
//     res.writeHead(302, { location: "/login" })
//     res.end()
//   } else {
//     var decoded = jwt.decode(token);
//     if (decoded.membership == 'inactive') {
//       const { res } = ctx
//       res.writeHead(302, { location: "/payment" })
//       res.end()
//     } else if (decoded.accstatus == 'pending') {
//       const { res } = ctx
//       res.writeHead(302, { location: "/setupacc" })
//       res.end()
//     }
//   }
//   return {
//     props: {}, // will be passed to the page component as props
//   }
// }