import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { Inter } from '@next/font/google'
import style from '@/styles/Home.module.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Grow Your Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/68c6324e4e.js" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <div className={style.container}>
        <div className={style.topbar}>
          <div className={style.ls}>
            <img src="/img/Group 12.png" alt="" />
          </div>
          <div className={style.rs}>
            <Link href="/login">
              <button className={style.bgMov}>
                <p>Loghează-te</p>
              </button>
            </Link>
            <Link href="/createaccount">
              <button className={style.bgMovDeschis}>
                <p>Creează Cont</p>
              </button>
            </Link>
          </div>
        </div>
        <div className={style.sc1} id="sc1">
          <div className={style.intro}>
            <img src="/img/Group 16.png" className={style.logo} alt="" />
            <p>pentru artisti &amp; producatori la inceput de drum</p>
          </div>
          <div className={style.scrollfm}>
            <div className={style.icons}>
              <i className="fa-solid fa-chevron-down" />
              <i className="fa-solid fa-chevron-down" />
              <i className="fa-solid fa-chevron-down" />
            </div>
            <p className={style.scrollfmp}>scroll pentru mai mult</p>
          </div>
        </div>
        <div className={style.sc2}>
          {/* <img src="/img/Group 12@2x.png" alt=""> */}
          <div className={style.offert}>
            <h2>
              Primii <span className={style.green}>500 de utilizatori</span> ce își creează
              cont beneficiază de un <span className={style.orange}>mare avantaj </span>în
              ambele clasamente.
            </h2>
            <p>
              Creează-ți acum contul, beneficiază de un avans în fața celorlalți
              artiști în ambele clasamente și bucură-te de cele 7 zile gratis!
            </p>
          </div>
          <div className={style.buttons}>
            <a href="/login">
              <button className={style.bgGreen}>
                <p>Loghează-te</p>
              </button>
            </a>
            <a href="/createaccount">
              <button className={style.bgOrange}>
                <p>Creează Cont</p>
              </button>
            </a>
          </div>
        </div>
        <div className={style.cards}>
          <div className={`${style.card} ${style.leftText}`}>
            <div className={style.content}>
              <div className={style.lp}>
                <h4 className={style.green}>CÂȘTIGĂ PREMII</h4>
                <h1>Obține premii de la nume mari din industria muzicala</h1>
                <p>
                  Colaborează, vinde și cumpără produse muzicale pentru a ajunge în
                  topul clasamentului și ai șansa de a obține premii de la
                  GrowYourMusic, WhoGotBars &amp; mulți alții. Mult succes!
                </p>
                <a href="/createaccount">
                  <button className={style.bgMov}>Creează Cont</button>
                </a>
              </div>
              <div className={style.rp}>
                <div className={style.shMov} />
                <i className="fa-solid fa-trophy" />
              </div>
            </div>
          </div>
          <div className={`${style.card} ${style.rightText}`}>
            <div className={style.content}>
              <div className={style.lp}>
                <i className="fa-solid fa-sack-dollar" />
              </div>
              <div className={style.rp}>
                <h4 className={style.orange}>SURSĂ DE BANI</h4>
                <h1>Câștigă bani prin vânzarea de produse/servicii muzicale</h1>
                <p>
                  Vândutul produselor sau al serviciilor muzicale te vor aduce în
                  topul Clasamentului Producătorilor, dar îți vor garanta și o sumă de
                  bani aleasă de tine pe fiecare contract încheiat!{" "}
                </p>
                <a href="/createaccount">
                  <button className={style.bgMovDeschis}>Creează Cont</button>
                </a>
              </div>
            </div>
          </div>
          <div className={`${style.card} ${style.leftText}`}>
            <div className={style.content}>
              <div className={style.lp}>
                <h4 className={style.green}>EVOLUEAZĂ</h4>
                <h1>Colaborează cu alți artiști și producători talentați</h1>
                <p>
                  Colaborarea este cheia succesului. Cooperează cu câți mai mulți
                  artiști/producători, lansează muzică de calitate pentru a-ți
                  dezvolta cariera și pentru a-ți crește punctele din Clasamentul
                  Artiștilor.
                </p>
                <a href="/createaccount">
                  <button className={style.bgMov}>Creează Cont</button>
                </a>
              </div>
              <div className={style.rp}>
                <i className="fa-solid fa-arrow-trend-up" />
              </div>
            </div>
          </div>
        </div>
        <footer className={style.footerr}>
          <img src="/img/Group 16.png" alt="" className={style.logoo} />
          <p>pentru artisti &amp; producatori la inceput de drum</p>
          <h1>SOCIAL MEDIA</h1>
          <div className={style.socialmed}>
            <img src="/img/Group_1.png" alt="" />
            <i className="fa-brands fa-instagram" />
            <i className="fa-brands fa-youtube" />
            <i className="fa-brands fa-tiktok" />
          </div>
          <h1>APLICAȚII</h1>
          <div className={style.app}>
            <i className="fa-brands fa-app-store-ios" />
            <img src="/img/logogym.png" alt="" />
            <i className="fa-brands fa-google-play" />
          </div>
          <h1>CONTACT</h1>
          <a href="emailto:contact@growyourmusic.ro">
            <h3>contact@growyourmusic.ro</h3>
          </a>
          <a href="#">
            <h3>Termeni și Condiții</h3>
          </a>
        </footer>
      </div>
      <Script
        src="/js/index.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
