import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/leaderboard.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Accept Contract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.leaderboard_artist}>
                    <div className={style.leaderboard}>
                      <div className={style.frow}>
                        <h1>Clasamentul Artiştilor</h1>
                        <div className={style.rfrow} id="changetoseller">
                          <h4>Vezi Clasamentul Producătorilor</h4>
                          <i className="fa-solid fa-arrow-right-long" />
                        </div>
                      </div>
                      <div className={style.leaderboard_fr}>
                        <ul>
                          <li className={style.n1}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#1</h1>
                              <h3 id="points">999 puncte</h3>
                            </div>
                          </li>
                          <li className={style.n2}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#2</h1>
                              <h3 id="points">998 puncte</h3>
                            </div>
                          </li>
                          <li className={style.n3}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#3</h1>
                              <h3 id="points">997 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li className={style.you}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 points</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 points</h3>
                            </div>
                          </li>

                        </ul>
                      </div>
                    </div>

                  </div>
                  <div className={style.leaderboard_seller}>
                    <div className={style.leaderboard}>
                      <div className={style.frow}>
                        <h1>Clasamentul Producătorilor</h1>
                        <div className={style.rfrow} id="changetoartist">
                          <h4>Vezi Clasamentul Artiștilor</h4>
                          <i className="fa-solid fa-arrow-right-long" />
                        </div>
                      </div>
                      <div className={style.leaderboard_fr}>
                        <ul>
                          <li className={style.n1}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#1</h1>
                              <h3 id="points">999 puncte</h3>
                            </div>
                          </li>
                          <li className={style.n2}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#2</h1>
                              <h3 id="points">998 puncte</h3>
                            </div>
                          </li>
                          <li className={style.n3}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#3</h1>
                              <h3 id="points">997 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li className={style.you}>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 puncte</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 points</h3>
                            </div>
                          </li>
                          <li>
                            <div className={style.l_side}>
                              <img src="/img/osky1.jpg" alt="" id="profilePic" />
                              <div className={style.l_side_r}>
                                <h2 id="stageName">LOREM123</h2>
                                <p id="username">loremipsum</p>
                              </div>
                            </div>
                            <div className={style.r_side}>
                              <h1 id="rank">#4</h1>
                              <h3 id="points">666 points</h3>
                            </div>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className={style.details}>
                      <div className={style.prizes}>
                        <h2>PREMII</h2>
                        <h1>
                          {" "}
                          - "Cum a fost creat produsul" X <b>WHOGOTBARS</b>{" "}
                        </h1>
                        <h1>
                          {" "}
                          - Contribuție + shout-out în piesa din Cl. artiștilor{" "}
                          <b>GrowYourMusic</b> (include Feature)
                        </h1>
                        <h1>
                          {" "}
                          - Vânzare specială a produselor în următorul sezon{" "}
                          <b>GrowYourMusic</b> (Special Shop){" "}
                        </h1>
                      </div>
                      <div className={style.desc}>
                        <h1>Cum să avansezi în clasamentul vânzătorilor:</h1>
                        <p>
                          Cooperarea este secretul succesului în clasament. Colaborează cât mai mult posibil pentru a urca în clasament. Acceptarea unei oferte primite valorează 4 puncte, iar trimiterea unei oferte care este acceptată, 2 puncte. Să
                          vedem cine va fi cel mai haladit artist. Mult succes!

                        </p>
                      </div>
                      <div className={style.timer}>
                        <h1>TIMP PÂNĂ LA FINALUL SEZONULUI </h1>
                        <h2>333 zile din 334 zile</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>

                <div className={style.news_card}>
                  <h1>Clasamentul Artiștilor</h1>
                  <p> Cooperarea este secretul succesului în clasament. Colaborează cât mai mult posibil pentru a urca în clasament. Acceptarea unei oferte primite valorează 4 puncte, iar trimiterea unei oferte care este acceptată, 2 puncte. Să
                    vedem cine va fi cel mai haladit artist. Mult succes!
                  </p>
                </div>
                <div className={style.news_card}>
                  <h1>Regulament Premii</h1>
                  <p> Premiile se vor acorda în funcție de poziționarea utilizatorilor în clasament.
                    Primul clasat va avea de ales între cele trei opțiuni, cel de al doilea va alege dintre cele două opțiuni rămase, iar cel de al treilea va primi premiul rămas.
                    Premiile se vor acorda pe parcursul sezonului actual și următorul sezon.
                    GrowYourMusic</p>
                </div>
                <div className={style.news_card}>
                  <h1>Premii</h1>
                  <div className={style.idk}>
                    <div>
                      <i className="fa-solid fa-question" />
                    </div>
                    <div>
                      <i className="fa-solid fa-question" />
                    </div>
                    <div>
                      <i className="fa-solid fa-question" />
                    </div>
                  </div>
                  <h2>ÎN CURÂND
                    <i className="fa-solid fa-clock" />
                  </h2>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
