import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/newchat.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
    return (
        <>
            <Head>
                <title>News Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div id="sc1" className={style.sc1}>
                <div className={style.main_container}>
                    <div className={style.navbar_contanier}>
                        <Navbar />
                    </div>
                    <div className={style.content_contanier}>
                        <div className={style.status_bar}>
                            <div className={style.greets_to_user}>
                                <p>Hello, Username</p>
                            </div>
                            <div className={style.container_searchbar}>
                                <div className={style.searchbox}>
                                    <AiOutlineSearch />
                                    <input
                                        type="text"
                                        placeholder='Explore'
                                        className={style.searchInput}
                                    />
                                </div>
                                <div className={style.user_btns}>
                                    <IoMdNotifications />
                                    <div className={style.user_pic}>
                                        <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className={style.feed_with_user}>
                            <div className={style.feed_posts}>


                            </div>
                            <div className={style.profile_bar}>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Script
                src="/js/animation.js"
                onLoad={() => {
                    console.log('Script has loaded')
                }}
            />
            <Script
                src="/js/useraccount.js"
                onLoad={() => {
                    console.log('Script has loaded')
                }}
            />
        </>
    )
}
