import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/newproduct.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>New Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explorează'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <Link href="shop">
                    <i className="fa-solid fa-assrrow-left-long back" />
                  </Link>

                  <div className={style.product} id="postCreate">
                    <div className={style.img_part}>
                      <i className="fa-solid fa-arrow-left-long aoleu" id="arrowLeft" />
                      <div className={style.img1}>
                        <input
                          type="file"
                          name="imgInput"
                          id="fileInputImg"
                          accept="image/png, image/jpeg, image/jpg"
                        />
                        <label htmlFor="fileInputImg">
                          <h3>Imagine</h3>
                          <i className="fa-solid fa-circle-plus" />
                        </label>
                        <div className={style.image}>
                          <img src="" alt="" id="imgP" />
                        </div>
                      </div>
                      <div className={style.img2}>
                        <input
                          type="file"
                          name="imgInput"
                          id="fileInputImg2"
                          accept="image/png, image/jpeg, image/jpg"
                        />
                        <label htmlFor="fileInputImg2">
                          <h3>Imagine</h3>
                          <i className="fa-solid fa-circle-plus" />
                        </label>
                        <div className={style.image2}>
                          <img src="" alt="" id="imgP2" />
                        </div>
                      </div>
                      <div className={style.vid1}>
                        <input
                          type="file"
                          name="videoInput"
                          id="fileInput3"
                          accept="video/mp4,video/x-m4v,video/*"
                        />
                        <label htmlFor="fileInput3">
                          <h3>Video</h3>
                          <i className="fa-solid fa-circle-plus" />
                        </label>
                        <video
                          preload="auto"
                          controlsList="nodownload"
                          disablePictureInPicture={true}
                          className={style.fixed_aspect_ratio}
                          id="videoP"
                        >
                          <source id="source" />
                        </video>
                      </div>
                      <i className="fa-solid fa-arrow-right-long" id="arrowRight" />
                    </div>

                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>
                <h2 className={style.titluproduse}>Detalii produs</h2>

                <div className={style.prodinput}>
                  <h3>Titlul produsului:</h3>
                  <input type="text" placeholder="Titlul produsului" />
                </div>
                <div className={style.prodinput}>
                  <h3>Preţul produsului:</h3>
                  <input type="text" placeholder="Preţul produsului" />
                </div>
                <div className={style.prodinput}>
                  <h3>Categoria produsului:</h3>
                  <select name="" id="">
                    <option value="None" selected>
                      --
                    </option>
                    <option value="Beats">Beats</option>
                    <option value="visual">Visual/Artwork</option>
                    <option value="mixmas">Mix Master</option>
                    <option value="musicvid">Music Video Edit</option>
                  </select>
                </div>
                <div className={style.prodinput}>
                  <h3>Descrierea produsului:</h3>
                  <textarea
                    name=""
                    id=""
                    cols={30}
                    rows={10}
                    placeholder="Descrierea produsului"
                    defaultValue={""}
                  />
                </div>
                <div className={style.prodinput}>
                  <input type="submit" defaultValue="Creează produsul" />
                </div>


              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/newproduct.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
