import Head from 'next/head'
import style from '../styles/payment.module.css'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
var jwt = require('jsonwebtoken');
import * as Yup from 'yup'
import Script from 'next/script'

const initialValues = {
  cardnumber: "",
  cardexpires: "",
  cardcvc: "",
}

export default function Home({ }) {

  const router = useRouter();

  const [username, setUsername] = useState()
  const [useremail, setUserEmail] = useState()


  const cardSchema = Yup.object({
    cardnumber: Yup.number().min(16, "It must be at least 6 char").required("Please Enter Card"),
    cardexpires: Yup.number().min(6, "It must be at least 6 char").max(25).required("Please Enter Password"),
    cardcvc: Yup.string().min(6, "It must be at least 6 char").max(25).required("Please Enter Password"),
  })

  // console.log(userdata);

  return (
    <>
      <Head>
        <title>Buy Membership -- Growyourmusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.container}>
        <div className={style.sc1} id="sc1">
          <div className={style.intro}>
            <h3>Creează Cont</h3>
            <form>
              <input
                type="text"
                placeholder="Numele Deținătorului"
                className={style.firstInput}
              />
              <input type="text" name="" id="" placeholder="Numărul Cardului" />
              <div className={style.flexInputs}>
                <input type="text" placeholder="CVC" maxLength={3} />
                <input type="text" placeholder="MM/YY" />
              </div>
              <input
                type="submit"
                value="Creează contul și plătește 50RON pe lună"
              />
              <div className={style.flex}>
                <input type="checkbox" name="" id="" className={style.checck} />
                <a href="#">
                  <h6>Acceptă Termenii și Condițiile</h6>
                </a>
              </div>
            </form>
            <img src="/img/Group 16.png" className={style.logo} alt="" />
            <p>pentru artisti &amp; producatori la inceput de drum</p>
          </div>
        </div>
      </div>

    </>
  )
}
