import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/productdetails.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Product Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.detailscard}>
                    <div id="img_part" className={style.img_part}>
                      <i className="fa-solid fa-arrow-left-long" id="arrowLeft" />
                      <div className={style.img1}>
                        <img src="/img/artist.png" alt="" id="img1" />
                      </div>
                      <div className={style.img2}>
                        <img src="/img/osky1.jpg" alt="" id="img2" />
                      </div>
                      <div className={style.vid1}>
                        <video
                          preload="auto"
                          controlsList="nodownload"
                          disablePictureInPicture={true}
                          className="fixed-aspect-ratio"
                          id="vid1"
                        >
                          <source src="/img/Pop Cola 2021 feat. ABI.mp4" />
                        </video>
                      </div>
                      <i className="fa-solid fa-arrow-right-long" id="arrowRight" />
                    </div>
                    <div className={style.last_part}>

                    </div>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>
                <h2 className={style.titluproduse}>Detalii produs</h2>
                <div className={style.productdetaill}>
                  <h3>Titlul produsului:</h3>
                  <h1 className={style.detail_title}>Voi face un beat pentru tine</h1>
                </div>
                <div className={style.productdetaill}>
                  <h3>Prețul produsului:</h3>
                  <h1 className={style.detail_price}>850 RON</h1>
                </div>
                <div className={style.productdetaill}>
                  <h3>Categoria produsului:</h3>
                  <h1 className={style.detail_categ}>Beat-uri</h1>
                </div>
                <div className={style.productdetaill}>
                  <h3>Rating-ul produsului:</h3>
                  <h1 className={style.detail_rating}>
                    5.0/5.0
                    <i className="fa-solid fa-music" style={{ marginLeft: 5 }} />
                  </h1>
                </div>
                <div className={style.productdetaill}>
                  <h3>Descrierea produsului:</h3>
                  <h1 className={style.detail_desc}>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi cum quos
                    corporis voluptatum, nesciunt dignissimos vel? Porro dignissimos quidem
                    reprehenderit a illo possimus quos unde, commodi repudiandae numquam qui
                    rem!
                  </h1>
                </div>

                <div className={style.lastrow}>
                  <div className={style.profile}>
                    <Link href="/userprofile">
                      <img src="/img/osky1.jpg" alt="" />
                    </Link>
                    <Link href="/userprofile">
                      <p>
                        <b>loremimpsum</b>
                      </p>
                    </Link>
                  </div>
                  <Link href="/chat">
                    <h2>
                      Ia legătura cu producătorul
                      <i className="fa-solid fa-arrow-right-long" />
                    </h2>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div >
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
      <Script
        src="/js/productdetails.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
