import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/review.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Accept Contract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.user_info}>
                    <div className={style.left}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.info}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p className={style.username}>loremipsum</p>
                      </div>
                    </div>
                    <div className={style.gotoprofile}>
                      <Link href="/userprofile">
                        <h4>Vizitează profilul</h4>{" "}
                        <i className="fa-solid fa-arrow-right-long" />{" "}
                      </Link>
                    </div>
                  </div>
                  <div className={style.chat} style={{ textAlign: "center" }}>
                    <h2 className={style.titlpag}>Produsul a fost livrat!</h2>
                    <Link href="/img/petrica.png" download="" className={style.downloadProd}>
                      <h3>
                        Click aici pentru a descărca produsul{" "}
                        <i className="fa-solid fa-download" style={{ marginLeft: 10 }} />
                      </h3>
                    </Link>
                    <h2 className={style.intrb}>
                      Cum ți s-a părut să lucrezi cu acest utilizator?
                    </h2>
                    <div>
                      <h3>
                        <select name="" id="">
                          <option value="" selected hidden>
                            0
                          </option>
                          <option value="">1</option>
                          <option value="">2</option>
                          <option value="">3</option>
                          <option value="">4</option>
                          <option value="">5</option>
                        </select>{" "}
                        /5 <i className="fa-solid fa-music" style={{ marginLeft: 5 }} />
                      </h3>
                    </div>
                    <h3 className={style.raporttitle}>Raportează (opțional): </h3>
                    <h4 className={style.timprap}>
                      Timpul de raportare a unei probleme la acest produs este de{" "}
                      <span>23 de ore</span> și <span>59 de minute</span>
                    </h4>
                    <select name="" id="" className={style.raport}>
                      <option value="" selected hidden>
                        Selectează motivul raportării
                      </option>
                      <option value="">Spam</option>
                      <option value="">Violență</option>
                      <option value="">Scam sau fraudă</option>
                      <option value="">Nuditate</option>
                      <option value="">Altceva</option>
                    </select>
                    <i className="fa-solid fa-arrow-right-long" id="sendraport" />
                    <br />
                    <Link href="/contracts">
                      <button>Încheie contractul</button>
                    </Link>
                    <h4 className={style.inccontr}>
                      <input type="checkbox" />
                      După încheierea contractului nu vei mai putea descărca acest produs.
                      Asigură-te că l-ai descărcat!
                    </h4>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>

                <div className={style.frow}>
                  <h5>Listă Contracte</h5>
                  <Link
                    href="/chat"
                    style={{
                      width: 180,
                      borderRadius: "5px",
                      cursor: "pointer",
                      display: "flex",
                      padding: "10px ",
                      color: "white",
                      backgroundColor: "#6657DA"
                    }}
                  >
                    <h4 style={{ fontSize: 14 }}>Verifică-ți mesajele</h4>
                    <i
                      className="fa-solid fa-arrow-right-long"
                      style={{ marginLeft: 145, marginTop: 3 }}
                    />
                  </Link>
                </div>
                <ul>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                </ul>

              </div>
            </div>
          </div>
        </div>
      </div >
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
