import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/sendprod.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Accept Contract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.user_info}>
                    <div className={style.left}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.info}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p className={style.username}>loremipsum</p>
                      </div>
                    </div>
                    <div className={style.gotoprofile}>
                      <Link href="/userprofile">
                        <h4>Vizitează profilul</h4>{" "}
                        <i className="fa-solid fa-arrow-right-long" />{" "}
                      </Link>
                    </div>
                  </div>
                  <div className={style.chat}>
                    <h2>
                      Contractul expiră în <span>23 de zile</span> <span>15 ore</span> și{" "}
                      <span>34 de minute</span>
                    </h2>
                    <div className={style.form}>
                      <label htmlFor="prodInput">
                        <h3
                          id="file-name"
                          style={{
                            marginTop: 10,
                            cursor: "pointer",
                            padding: "10px 20px",
                            border: "#6c5ce7 1px solid"
                          }}
                        >
                          Încarcă produsul aici
                          <i className="fa-solid fa-circle-plus" style={{ marginLeft: 10 }} />
                        </h3>
                      </label>
                      <p className={style.error}>Asigură-te că ai încărcat produsul</p>
                      <input type="file" id="prodInput" style={{ display: "none" }} />
                      <br />
                      <h3>
                        Ești sigur sigur că acest fișier vrei să fie trimis ca produsul final?
                      </h3>
                      <div style={{ display: "flex", justifyContent: "center" }}>
                        <h3>
                          <input type="checkbox" name="" id="" style={{ marginRight: 5 }} />
                          Da, acest fișier va fi trimis ca produs final
                        </h3>
                      </div>
                      <p className={style.error2}>Asigură-te că ai bifat căsuța liberă</p>
                      <Link href="/moneyws">
                        <button className={style.sendProd}>Trimite produsul</button>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>
                <div className={style.user_detail}>
                  <div className={style.user_list}>
                    <Link
                      href="/chat"
                      style={{
                        width: 170,
                        display: "flex",
                        borderBottom: "1px solid #2a2a2a",
                        color: "#2a2a2a"
                      }}
                    >
                      <h4 style={{ fontSize: 14 }}>Verifică-ți mesajele</h4>
                      <i
                        className="fa-solid fa-arrow-right-long"
                        style={{ marginLeft: 10 }}
                      />
                    </Link>
                    <ul>
                      <Link href="#">
                        <li className={`${style.get} ${style.notif}`}>
                          <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                          <div className={style.message}>
                            <h1 className={style.artistname}>LOREM123</h1>
                            <p>contract primit</p>
                          </div>
                        </li>
                      </Link>

                      <li className={style.send}>
                        <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                        <div className={style.message}>
                          <h1 className={style.artistname}>LOREM123</h1>
                          <p>contract trimis</p>
                        </div>
                      </li>

                      <li className={style.send}>
                        <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                        <div className={style.message}>
                          <h1 className={style.artistname}>LOREM123</h1>
                          <p>contract trimis</p>
                        </div>
                      </li>
                      <Link href="#">
                        <li className={`${style.get} ${style.notif}`}>
                          <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                          <div className={style.message}>
                            <h1 className={style.artistname}>LOREM123</h1>
                            <p>contract primit</p>
                          </div>
                        </li>
                      </Link>
                      <li className={style.send}>
                        <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                        <div className={style.message}>
                          <h1 className={style.artistname}>LOREM123</h1>
                          <p>contract trimis</p>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </>
  )
}
