import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/settings.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/68c6324e4e.js"></script>
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.l_side}>
                    <div className={`${style.card} ${style.change_pw}`}>
                      <h1 className={style.card_title}>Schimbă parola</h1>
                      <input type="password" id="oldpw" placeholder="Parola veche" />
                      <input type="password" id="newpw" placeholder="Parola nouă" />
                      <input type="password" id="newpw2" placeholder="Parola nouă" />
                      <input type="submit" defaultValue="Schimbă" />
                    </div>
                    <div className={`${style.wallet} ${style.card}`}>
                      <h1 className={style.card_title}>Portofel</h1>
                      <div className={style.srow}>
                        <div className={style.totalbalance}>
                          <h3>Balanţa totală:</h3>
                          <h2>123,8$</h2>
                        </div>
                        <div className={style.actions}>
                          <Link href="withdraw">
                            <button>Retragere</button>
                          </Link>
                          <Link href="deposit">
                            <button>Depozitează</button>
                          </Link>
                        </div>
                      </div>
                    </div>
                    <div className={`${style.contact_form} ${style.card}`}>
                      <h1 className={style.card_title}>Contact</h1>
                      <textarea
                        name=""
                        id=""
                        cols={30}
                        rows={10}
                        placeholder="Scrie mesajul"
                        defaultValue={""}
                      />
                      <br />
                      <div style={{ display: "flex" }}>
                        <p style={{ color: "#6c5ce7" }}>sau</p>
                        <Link
                          style={{ color: "#6c5ce7", marginLeft: 5 }}
                          href="mailto:growyourmusic.official@gmail.com"
                        >
                          <p>trimite mail aici</p>
                        </Link>
                      </div>
                      <input type="submit" defaultValue="Trimite" />
                    </div>
                  </div>

                </div>
              </div>
              <div className={style.profile_bar}>

                <div className={style.frow}>
                  <h5>Listă Contracte</h5>
                  <Link
                    href="/chat"
                    style={{
                      width: 180,
                      borderRadius: "5px",
                      cursor: "pointer",
                      display: "flex",
                      padding: "10px ",
                      color: "white",
                      backgroundColor: "#6657DA"
                    }}
                  >
                    <h4 style={{ fontSize: 14 }}>Verifică-ți mesajele</h4>
                    <i
                      className="fa-solid fa-arrow-right-long"
                      style={{ marginLeft: 145, marginTop: 3 }}
                    />
                  </Link>
                </div>
                <div className={`${style.card} ${style.faq}`}>
                  <h1 className={style.card_title}>FAQ</h1>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                  <div className={style.q1}>
                    <h1>1. How do I create an account?</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita
                      molestiae dolore veniam, repudiandae recusandae saepe quidem est illum
                      necessitatibus eveniet. Eveniet enim in obcaecati fuga ipsum, ratione
                      reiciendis eaque sapiente!
                    </p>
                  </div>
                </div>
                <div className={style.r_side}>

                  <h1 className={style.sure}>Eşti sigur?</h1>
                  <div className={style.delete_acc}>
                    <button id="logout">Deconectaţi-vă</button>
                    <button id="delacc">Şterge contul</button>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </div>
  )
}
