import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/shop.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="sc1" className={style.sc1}>
        <div className={style.main_container}>
          <div className={style.navbar_contanier}>
            <Navbar />
          </div>
          <div className={style.content_contanier}>
            <div className={style.status_bar}>
              <div className={style.greets_to_user}>
                <p>Hello, Username</p>
              </div>
              <div className={style.container_searchbar}>
                <div className={style.searchbox}>
                  <AiOutlineSearch />
                  <input
                    type="text"
                    placeholder='Explore'
                    className={style.searchInput}
                  />
                </div>
                <div className={style.user_btns}>
                  <IoMdNotifications />
                  <div className={style.user_pic}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.feed_with_user}>
              <div className={style.feed_posts}>
                <div className={style.dm}>
                  <div className={style.filter}>
                    <Link href="/newproduct">
                      <i className="far fa-plus-square" />
                    </Link>
                    <div className={style.left}>
                      <select name="" id="products">
                        <option value="all">Toate </option>
                        <option value="beats">Beats</option>
                        <option value="visual">Visual/Artwork</option>
                        <option value="musicvidedit">Music Video Edit</option>
                        <option value="mixmas">Mix Master</option>
                      </select>
                      {/* <i className="fa-solid fa-angle-down" id="selectDown" /> */}
                    </div>
                  </div>
                  <div className={style.products}>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={style.product}>
                      <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                      <div className={style.details_prod}>
                        <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                        <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                        <div className={style.bottom_part}>
                          <div className={style.profile}>
                            <img src="/img/osky1.jpg" alt=" " />
                            <div className={style.username}>
                              <p><b>lorem ipsum</b></p>
                            </div>
                          </div>
                          <div className={style.details_prod_check}>
                            <Link href="/productdetails">
                              <h4>Vezi detalii</h4>
                              <i className="fa-solid fa-arrow-right-long" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className={style.profile_bar}>

                <div className={style.frow}>
                  <h5>Listă Contracte</h5>
                  <Link
                    href="/chat"
                    style={{
                      width: 180,
                      borderRadius: "5px",
                      cursor: "pointer",
                      display: "flex",
                      padding: "10px ",
                      color: "white",
                      backgroundColor: "#6657DA"
                    }}
                  >
                    <h4 style={{ fontSize: 14 }}>Verifică-ți mesajele</h4>
                    <i
                      className="fa-solid fa-arrow-right-long"
                      style={{ marginLeft: 145, marginTop: 3 }}
                    />
                  </Link>
                </div>
                <ul>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>

                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                  <Link href="#">
                    <li className={`${style.get} ${style.notif}`}>
                      <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                      <div className={style.message}>
                        <h1 className={style.artistname}>LOREM123</h1>
                        <p>contract primit</p>
                      </div>
                    </li>
                  </Link>
                  <li className={style.send}>
                    <img src="/img/osky1.jpg" alt="" className={style.profileImg} />
                    <div className={style.message}>
                      <h1 className={style.artistname}>LOREM123</h1>
                      <p>contract trimis</p>
                    </div>
                  </li>
                </ul>

              </div>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="/js/animation.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
    </>
  )
}
