import Head from 'next/head'
import { AiOutlineSearch } from "react-icons/ai";
import { IoMdNotifications } from "react-icons/io";
import style from '../styles/useraccount.module.css'
import Navbar from '../components/navbar'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
    return (
        <>
            <Head>
                <title>News Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div id="sc1" className={style.sc1}>
                <div className={style.main_container}>
                    <div className={style.navbar_contanier}>
                        <Navbar />
                    </div>
                    <div className={style.content_contanier}>
                        <div className={style.status_bar}>
                            <div className={style.greets_to_user}>
                                <p>Hello, Username</p>
                            </div>
                            <div className={style.container_searchbar}>
                                <div className={style.searchbox}>
                                    <AiOutlineSearch />
                                    <input
                                        type="text"
                                        placeholder='Explore'
                                        className={style.searchInput}
                                    />
                                </div>
                                <div className={style.user_btns}>
                                    <IoMdNotifications />
                                    <div className={style.user_pic}>
                                        <img src="/img/osky1.jpg" alt="" className={style.profileimg} />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className={style.feed_with_user}>
                            <div className={style.feed_posts}>
                                <div className={style.dm}>
                                    <div className={style.postsorprods}>
                                        <button id='posts' style={{
                                            backgroundColor: '#6657DA',
                                            cursor: 'default'
                                        }}>
                                            <b>Postări</b>
                                        </button>
                                        <button id='prods' style={{
                                            backgroundColor: 'transparent',
                                            cursor: 'pointer'
                                        }}>
                                            <b>Produse</b>
                                        </button>
                                    </div>
                                    <div className={style.posts} id="postsDiv">
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                        <div className={style.post}>
                                            <img src="/img/artwork.jpeg" alt="" />
                                        </div>
                                    </div>
                                    <div className={style.products} id="productsDiv">
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={style.product}>
                                            <img src="/img/artwork.jpeg" className={style.productMainImg} alt=" " />
                                            <div className={style.details_prod}>
                                                <h1 className={style.prodTitle}>Voi face un beat pentru tine</h1>
                                                <p id="price" className={style.priiice}><b>Preţ:</b> 850 RON</p>
                                                <div className={style.bottom_part}>
                                                    <div className={style.profile}>
                                                        <img src="/img/osky1.jpg" alt=" " />
                                                        <div className={style.username}>
                                                            <p><b>lorem ipsum</b></p>
                                                        </div>
                                                    </div>
                                                    <div className={style.details_prod_check}>
                                                        <Link href="/productdetails">
                                                            <h4>Vezi detalii</h4>
                                                            <i className="fa-solid fa-arrow-right-long" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className={style.profile_bar}>
                                <div className={style.div_info2}>
                                    <img src="/img/artwork.jpeg" alt="" className={style.imgBg} />
                                    <img src="/img/artwork.jpeg" alt="" className={style.imgPrinc} />
                                </div>
                                <div className={style.div_info}>

                                    <h1 className={style.h12}>STAGE NAME</h1>
                                    <h1 className={style.h11}>STAGE NAME</h1>
                                </div>
                                <div className={style.div_info}>
                                    <p className={style.username}>
                                        <b>@loremipsum</b>
                                    </p>

                                </div>
                                <div className={style.div_info}>
                                    <p>Preț de colaborare:</p>
                                    <h2>2400 RON</h2>
                                </div>
                                <div className={style.div_info}>
                                    <p>Descriere:</p>
                                    <h6>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam repellat velit nobis fugiat molestiae, nam deserunt ipsa expedita aliquam perspiciatis libero eveniet culpa magni magnam tempore quia aut eum accusantium.</h6>
                                </div>
                                <div className={style.flex}>
                                    <div className={style.div_info}>
                                        <p>Clasamentul Artiștilor:</p>
                                        <h2>#1</h2>
                                    </div>
                                    <div className={style.div_info}>
                                        <p>Clasamentul Producătorilor:</p>
                                        <h2>#24</h2>
                                    </div>
                                </div>
                                <div className={style.flex}>
                                    <button>
                                        Urmărește
                                    </button>
                                    <button>
                                        Mesaj
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Script
                src="/js/animation.js"
                onLoad={() => {
                    console.log('Script has loaded')
                }}
            />
            <Script
                src="/js/useraccount.js"
                onLoad={() => {
                    console.log('Script has loaded')
                }}
            />
        </>
    )
}
